module.exports={
    STUDENT_COLLECTION:'students',
    DOUBT_COLLECTION:'doubts',
    TEACHER_COLLECTION:'teacher',
    ADMIN_COLLECTION:'admin',
    ANSWER_COLLECTION:'answer',
    RATING_COLLECTION:'rating',
    ANSWER_RATING_COLLECTION:'answer_ratings',
    OTP_COLLECTION:'otps'
}